// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfKff_5cB86vBOxSghaDojyXyGsS9ACwY',
    appId: '1:338166352732:web:95abf5c131f9caf9d08f99',
    messagingSenderId: '338166352732',
    projectId: 'kopma-uin-suka-cc3da',
    authDomain: 'kopma-uin-suka-cc3da.firebaseapp.com',
    storageBucket: 'kopma-uin-suka-cc3da.appspot.com',
    measurementId: 'G-V2EELC6GBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHAAN6AZAGZ6AOYrTBR8YN0NSoTjZjqo8',
    appId: '1:338166352732:android:0ec1dfd2e19df69fd08f99',
    messagingSenderId: '338166352732',
    projectId: 'kopma-uin-suka-cc3da',
    storageBucket: 'kopma-uin-suka-cc3da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpolK3_FLDdyWNNrDtIoOeKZ5k12X9Dl4',
    appId: '1:338166352732:ios:245af15b1bf82e04d08f99',
    messagingSenderId: '338166352732',
    projectId: 'kopma-uin-suka-cc3da',
    storageBucket: 'kopma-uin-suka-cc3da.appspot.com',
    iosClientId:
        '338166352732-pmf981j5eh8e23qenpni8ua6n40rgmuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopma',
  );
}

const iOSClientId = 'your-client-id.apps.googleusercontent.com';
const webClientId =
    '338166352732-ijvnvvj8p1qiddu9si8k8s3sva9hava0.apps.googleusercontent.com';

String get googleClientId {
  return switch (defaultTargetPlatform) {
    TargetPlatform.iOS || TargetPlatform.macOS => iOSClientId,
    _ => webClientId,
  };
}
